#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/mysql'
mod 'puppetlabs/apache'
mod 'puppetlabs/firewall'
mod 'git', :git => 'https://github.com/example42/puppet-git.git'
mod 'php', :git => 'https://github.com/example42/puppet-php.git'
mod 'txtcmdr', :git => 'https://github.com/lbhurtado/puppet-txtcmdr.git'
mod 'custom', :git => 'https://github.com/lbhurtado/puppet-txtcmdr-custom.git'
mod 'composer', :git => 'git://github.com/willdurand/puppet-composer.git'
mod 'symfony', :git => 'https://github.com/vagrantee/puppet-symfony.git'
mod 'smstools', :git => 'https://github.com/lbhurtado/puppet-smstools.git'
mod 'postfix', :git => 'https://github.com/example42/puppet-postfix.git'
mod 'dovecot', :git => 'https://github.com/example42/puppet-dovecot.git'